GET http://localhost:5000/notes

###
GET http://localhost:5000/notes/1

###
POST https://notes-be-353267785618.us-central1.run.app/register
Content-Type: application/json
{
    "username": "davidimhut",
    "password": "12345",
    "confirmPassword" : "12345"
}

###
POST https://notes-be-353267785618.us-central1.run.app/login
Content-Type: application/json

{
    "email": "david@gmail.com",
    "password": "david"
}

###
PATCH http://localhost:5000/notes/1
Content-Type: application/json

{
    "nama": "Dapidd", 
    "judul": "Hari Pertama", 
    "isi": "Mohon maaf lahir dan batin"
}

###
DELETE http://localhost:5000/notes/2